#!/bin/bash
#SBATCH --job-name=ATACseq_PCR_duplicates_removal        # Job name
#SBATCH -A BLUMBERG_LAB              # Account to charge
#SBATCH -p standard                   # Partition name
#SBATCH --array=0-23                 # Adjust to number of samples - 1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=48GB
#SBATCH --error=slurm-%A_%a.err
#SBATCH --output=slurm-%A_%a.out

module load samtools/1.15.1 picard-tools/3.3.0

echo "Job started at $(date)"

#picard path
PICARD_JAR="/opt/apps/picard-tools/3.3.0/picard.jar"

#set variables to store files
bam_dir="/share/crsp/lab/blumberg/share/mtDNAremoved_bams"
dedup_dir="/share/crsp/lab/blumberg/share/dedup_bam"

mkdir -p "$dedup_dir"

#get sample names from BAM files
bams=(${bam_dir}/*.mtDNArmvd.sortedByCoord.bam)
in_bam="${bams[$SLURM_ARRAY_TASK_ID]}"

#safety check
[[ ! -f "$in_bam" ]] && {
    echo "ERROR: BAM not found for ${SLURM_ARRAY_TASK_ID}"
    exit 1
}

#get sample name
sample=$(basename "$in_bam" .mtDNArmvd.sortedByCoord.bam)
out_bam="${dedup_dir}/${sample}.dedup.bam"
metrics="${dedup_dir}/${sample}_marked_dup_metrics.txt"

#skip if already exists                                                                                                                                                                                                                              
if [[ -f "$out_bam" ]]; then
    echo "$out_bam already exists, skipping..."
    exit 0
fi

echo "Removing PCR duplicates from $sample ..."

#create a unique temporary folder for Picard
TMP_DIR="/tmp/${SLURM_JOB_ID}_${SLURM_ARRAY_TASK_ID}"
mkdir -p "$TMP_DIR"

#run Picard MarkDuplicates
java -jar "$PICARD_JAR" MarkDuplicates \
    I="$in_bam" \
    O="$out_bam" \
    M="$metrics" \
    ASSUME_SORT_ORDER=coordinate \
    REMOVE_DUPLICATES=true \
    CREATE_INDEX=false \
    TMP_DIR="$TMP_DIR"

#index with samtools
samtools index "$out_bam"

#clean up temporary directories
rm -rf "$TMP_DIR"

echo "Job finished at $(date)"
