#!/bin/bash
#SBATCH --job-name=trimmed_fastqc_job       ## Name of the job
#SBATCH -A galongo      ## account to charge
#SBATCH -p free               ## partition name
#SBATCH --nodes=1             ## (-N) number of nodes to use
#SBATCH --ntasks=1            ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=1     ## number of cores the job needs
#SBATCH --error=slurm-%J.err  ## error log file
#SBATCH --output=slurm-%J.out ## output log file

#set variables for where to find and store files
origin_path='/pub/galongo/ATAC-seq/trimmed_fastq'
base_path='/share/crsp/lab/blumberg/share'

#load fastqc
module load fastqc/0.11.9

echo "Job started at $(date)"

#command to analyze entire folder with fastqc at once
fastqc $origin_path/*.fq.gz --outdir $base_path/trimmed_fastqc

echo "Job finished at $(date)"
